name: Weekly Commit Check

on:
  schedule:
    - cron: '0 0 * * 0' # Runs at 00:00 every Sunday

jobs:
  check-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          repository: 'jrbudda/Vivecraft_Spigot_Extensions'
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Get commits from the last week starting 2024
        id: get-commits
        run: |
          commits=$(git log --since='1 week ago' --after='2024-01-01' --pretty=format:"- [%h](https://github.com/jrbudda/Vivecraft_Spigot_Extensions/commit/%H) %s")
          if [[ -z "$commits" ]]; then
            echo "No new commits found."
            echo "::set-output name=commits::"
          else
            echo "::set-output name=commits::$commits"
          fi

      - name: Create issue with commits
        if: steps.get-commits.outputs.commits != ''
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.VIVECRAFT_SPIGOT }}
          script: |
            const issueBody = `
            ## Updated Upstream (VSE)

            ### Commits from the last week:

            ${process.env.COMMITS}

            Please review the above commits for potential updates to our fork.
            `;

            github.issues.create({
              owner: 'CJCrafter',
              repo: 'VivecraftSpigot',
              title: 'Updated Upstream (VSE)',
              body: issueBody,
              labels: ['upstream-updates'],
            });
        env:
          COMMITS: ${{ steps.get-commits.outputs.commits }}
